# Generated by Django 5.2.8 on 2025-11-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0006_sucursal_remove_auto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='color',
        ),
    ]
